version: '3.8'

services:
  nodejs-dev:
    build: .
    container_name: ${CONTAINER_NAME:-nodejs-dev}
    volumes:
      - ${SOURCE_CODE_PATH}:/workspace
      - node-modules:/workspace/node_modules
    working_dir: /workspace
    ports:
      - "${APP_PORT:-3000}:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: tail -f /dev/null
    networks:
      - dev-network

volumes:
  node-modules:

networks:
  dev-network:
    driver: bridge
